/**
 * Types for the proposed workflow list generated by Agent 1 (Dataverse Expert).
 *
 * After analysing the solution structure, the pipeline proposes a set of
 * training workflows. Consultants review, reorder, rename, and select
 * which workflows to include before the walkthrough is generated.
 */

/** A single proposed workflow as returned by the backend. */
export interface ProposedWorkflow {
  /** Unique identifier for this workflow. */
  id: string;
  /** Short human-readable name (editable by consultant). */
  name: string;
  /** Longer description of what this workflow covers (editable). */
  description: string;
  /** The primary entity/table this workflow relates to. */
  primary_entity: string;
  /** Display name of the primary entity. */
  primary_entity_display_name: string;
  /** Related entities involved in this workflow. */
  related_entities: string[];
  /** Estimated number of walkthrough steps for this workflow. */
  estimated_steps: number;
  /** Whether this workflow was auto-selected by the AI. */
  ai_recommended: boolean;
  /** Sort order as proposed by the AI (0-based). */
  sort_order: number;
  /** Tags indicating workflow category (e.g. "CRUD", "approval", "lookup"). */
  tags: string[];
  /** AI confidence score for this workflow (0.0 – 1.0). */
  confidence: number;
  /** Gap warning if the AI detected sparse/missing components. */
  gap_warning?: string | null;
}

/** Backend response for the proposed workflow list. */
export interface ProposedWorkflowsResponse {
  project_id: string;
  run_id: string;
  workflows: ProposedWorkflow[];
  total_count: number;
}

/** Request body to confirm the selected/reordered workflows. */
export interface WorkflowSelectionRequest {
  /** Ordered list of workflow IDs that the consultant has selected. */
  selected_workflow_ids: string[];
  /** Per-workflow overrides for name/description edits. */
  overrides: WorkflowOverride[];
}

/** A consultant's override for a single workflow's name/description. */
export interface WorkflowOverride {
  workflow_id: string;
  name?: string;
  description?: string;
}

/** Response after confirming workflow selection. */
export interface WorkflowSelectionResponse {
  project_id: string;
  run_id: string;
  selected_count: number;
  /** The next pipeline stage URL or identifier. */
  next_step: string;
}

// ── Confirm workflows + trigger pipeline ──────────────────────────────

/** Request body for the combined confirm-and-generate endpoint. */
export interface WorkflowConfirmRequest {
  /** Ordered list of workflow IDs the consultant selected. */
  selected_workflow_ids: string[];
  /** Per-workflow name/description overrides. */
  overrides: WorkflowOverride[];
  /** The selected app module unique name. */
  app_unique_name: string;
}

/** Response from the confirm endpoint — includes pipeline run info. */
export interface WorkflowConfirmResponse {
  project_id: string;
  /** Pipeline run ID for SSE progress tracking. */
  run_id: string;
  /** Number of confirmed workflows. */
  selected_count: number;
  /** SSE endpoint URL for real-time pipeline progress. */
  sse_url: string;
  /** Initial pipeline stage. */
  stage: string;
}

// ── Frontend-only state ──────────────────────────────────────────────

/** Extended workflow item with frontend selection/editing state. */
export interface WorkflowItem extends ProposedWorkflow {
  /** Whether the consultant has selected this workflow. */
  selected: boolean;
  /** Consultant-edited name (undefined = unchanged from AI). */
  editedName?: string;
  /** Consultant-edited description (undefined = unchanged from AI). */
  editedDescription?: string;
}
