"use client";

/**
 * Invite landing page — orchestrates the end-user onboarding flow:
 *
 * 1. Validates the invite token
 * 2. Shows loading state while validating
 * 3. Shows error state if the token is invalid/expired/revoked
 * 4. Shows the identity capture form if the token is valid
 * 5. Redirects to training walkthrough on successful identity capture
 */

import { useCallback, useEffect, useState } from "react";
import {
  Spinner,
  makeStyles,
  tokens,
} from "@fluentui/react-components";
import { validateInviteToken, ApiError } from "@/lib/api";
import type {
  InviteValidateResponse,
  IdentityCaptureResponse,
} from "@/types/end-user";
import { IdentityCaptureForm } from "./IdentityCaptureForm";
import { InviteErrorState } from "./InviteErrorState";

/**
 * Validates the invite token format client-side before hitting the API.
 *
 * Tokens are generated by `secrets.token_urlsafe(32)` which produces
 * a 43-character base64url string. We accept tokens between 20–128
 * characters using only URL-safe base64 characters to filter obviously
 * malformed tokens without an API round-trip.
 */
const TOKEN_FORMAT_REGEX = /^[A-Za-z0-9_-]{20,128}$/;

function isValidTokenFormat(token: string): boolean {
  return TOKEN_FORMAT_REGEX.test(token);
}

const useStyles = makeStyles({
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    backgroundColor: tokens.colorNeutralBackground2,
    gap: "16px",
  },
});

interface InviteLandingPageProps {
  token: string;
}

type PageState =
  | { kind: "loading" }
  | { kind: "valid"; data: InviteValidateResponse }
  | { kind: "error"; data: InviteValidateResponse }
  | { kind: "network_error"; message: string }
  | {
      kind: "seat_limit_reached";
      detail: string;
      projectName: string | null;
      adminContactEmail: string | null;
    };

export function InviteLandingPage({ token }: InviteLandingPageProps) {
  const styles = useStyles();
  const [state, setState] = useState<PageState>({ kind: "loading" });

  // ── Validate invite token on mount ─────────────────────────────

  useEffect(() => {
    let cancelled = false;

    async function validate() {
      // Client-side token format check — reject obviously malformed
      // tokens without an API round-trip
      if (!isValidTokenFormat(token)) {
        setState({
          kind: "error",
          data: {
            valid: false,
            status: "invalid_format",
            project_name: null,
            project_id: null,
            label: null,
            expires_at: null,
            seats_available: false,
            error_code: "INVALID_TOKEN_FORMAT",
            error_message:
              "This invite link appears to be malformed. Please check the URL and try again, or request a new link from your administrator.",
          },
        });
        return;
      }

      try {
        const result = await validateInviteToken(token);
        if (cancelled) return;

        if (result.valid) {
          setState({ kind: "valid", data: result });
        } else {
          setState({ kind: "error", data: result });
        }
      } catch (err) {
        if (cancelled) return;
        const message =
          err instanceof ApiError
            ? err.message
            : "Unable to validate invite link. Please try again.";
        setState({ kind: "network_error", message });
      }
    }

    validate();
    return () => {
      cancelled = true;
    };
  }, [token]);

  // ── Handle successful identity capture ─────────────────────────

  const handleSuccess = useCallback(
    (response: IdentityCaptureResponse) => {
      // Short delay so the user sees the success state, then redirect
      // to the consent prompt screen where the user must accept privacy
      // policy and terms before accessing training content.
      setTimeout(() => {
        window.location.href = `/consent/${response.seat_id}`;
      }, 1500);
    },
    []
  );

  // ── Handle seat-limit race condition ──────────────────────────
  // Seats can fill up between initial token validation (which passed)
  // and the identity capture submission. When the backend returns 403,
  // IdentityCaptureForm calls this callback so we transition to the
  // hard-block screen.

  const handleSeatLimitReached = useCallback(
    (detail: string, adminContactEmail?: string | null) => {
      // Use admin email from the 403 response if available, otherwise
      // fall back to whatever was in the initial validation response.
      const projectName =
        state.kind === "valid" ? state.data.project_name : null;
      const resolvedAdminEmail =
        adminContactEmail ??
        (state.kind === "valid" ? state.data.admin_contact_email : null);

      setState({
        kind: "seat_limit_reached",
        detail,
        projectName,
        adminContactEmail: resolvedAdminEmail,
      });
    },
    [state]
  );

  // ── Render ─────────────────────────────────────────────────────

  switch (state.kind) {
    case "loading":
      return (
        <div className={styles.loadingContainer}>
          <Spinner size="large" label="Validating invite link..." />
        </div>
      );

    case "valid":
      return (
        <IdentityCaptureForm
          token={token}
          projectName={state.data.project_name}
          onSuccess={handleSuccess}
          onSeatLimitReached={handleSeatLimitReached}
        />
      );

    case "error":
      return (
        <InviteErrorState
          errorCode={state.data.error_code}
          errorMessage={state.data.error_message}
          projectName={state.data.project_name}
          adminContactEmail={state.data.admin_contact_email}
        />
      );

    case "seat_limit_reached":
      return (
        <InviteErrorState
          errorCode="NO_SEATS_AVAILABLE"
          errorMessage={state.detail}
          projectName={state.projectName}
          adminContactEmail={state.adminContactEmail}
        />
      );

    case "network_error":
      return (
        <InviteErrorState
          errorCode="NETWORK_ERROR"
          errorMessage={state.message}
          projectName={null}
        />
      );
  }
}
